language: node_js
os: osx
node_js:
- '6.11.1'
before_install:
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
script:
- yarn test-ci
after_script:
- greenkeeper-lockfile-upload
- yarn codecov
branches:
  only:
  - master
  - develop
  - beta
  - "/^greenkeeper\\/.*$/"
deploy:
  provider: script
  script: yarn deploy-beta
  on:
    branch: beta
