// flow-typed signature: 0a06b91666d48ca4cb93a3b4aa3a50b5
// flow-typed version: <<STUB>>/expo_v17.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare type ImagePickerOptions = {
    allowsEditing?: boolean,
    aspect?: [number, number],
  };

  declare type ImagePickerResult = {
    cancelled: true,
  } | {
    cancelled: false,
    height: number,
    width: number,
    uri: string,
  };

  declare export var ImagePicker: {
    launchImageLibraryAsync: (options?: ImagePickerOptions) => Promise<ImagePickerResult>,
  }
}
