// flow-typed signature: 039e48ca6a676b1f2c4d37b9309cd35b
// flow-typed version: <<STUB>>/react-native-status-bar-size_v0.3.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-status-bar-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-status-bar-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-status-bar-size/StatusBarSizeIOS' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-status-bar-size/StatusBarSizeIOS.js' {
  declare module.exports: $Exports<'react-native-status-bar-size/StatusBarSizeIOS'>;
}
