# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

default_platform :ios

lane :beta do
  cocoapods

  increment_build_number

  gym(
    scheme: "bos311",
    export_method: "ad-hoc"
  )

  crashlytics(
    api_token: ENV['FABRIC_API_KEY'],
    build_secret: ENV['FABRIC_BUILD_SECRET']
  )
end

lane :device_update do
  gym(
    scheme: "bos311",
    export_method: "ad-hoc"
  )

  crashlytics(
    api_token: ENV['FABRIC_API_KEY'],
    build_secret: ENV['FABRIC_BUILD_SECRET']
  )
end